"""
Advance Quiz Bot — Open Source Project
This project was originally developed by Gagan (github.com/devgaganin).
Reference: https://t.me/advance_quiz_bot
The codebase has been reviewed and verified with the assistance of Claude AI.
"""

from __future__ import annotations

from typing import Optional
from urllib.parse import quote

from . import config


def is_enabled() -> bool:
    return bool(config.MINI_APP_DOMAIN)


def mini_app_play_url(qid: str, mode: str = "practice") -> Optional[str]:
    """Direct HTTPS URL to the play page for a quiz. None if disabled."""
    if not config.MINI_APP_DOMAIN:
        return None
    domain = config.MINI_APP_DOMAIN.rstrip("/")
    if not domain.startswith("http"):
        domain = f"https://{domain}"
    mode = mode if mode in ("practice", "exam") else "practice"
    return f"{domain}/play/{quote(qid, safe='')}?mode={mode}"


def mini_app_web_app_button(bot_username_unused: str, qid: str, mode: str, label: Optional[str] = None):
    """A native `web_app` InlineKeyboardButton -- only safe to attach to a
    message sent directly in a private chat with the bot. Returns None if
    the Mini App is not configured.

    Imports pyrogram lazily so this module stays importable from contexts
    (like the Mini App itself, or the Runner Bot) that don't have pyrogram
    installed.
    """
    url = mini_app_play_url(qid, mode)
    if not url:
        return None
    from pyrogram.types import InlineKeyboardButton, WebAppInfo

    text = label or ("Play (Practice)" if mode == "practice" else "Play (Exam)")
    return InlineKeyboardButton(text, web_app=WebAppInfo(url=url))


def _startapp_payload(qid: str, mode: str) -> str:
    """Encode (qid, mode) into a `startapp` deep-link payload.

    Telegram restricts this payload to `A-Z a-z 0-9 _ -` and a 64-char
    max (see core.telegram.org/bots/features, "Deep Linking"). Quiz IDs
    generated by this bot are always alphanumeric (`GGN` + 6 upper-case
    alphanumerics, or a 10-char lowercase hex slice -- see
    creator_bot/handlers/quiz_creation.py and database/repositories.py),
    so a simple `play_<qid>_<mode>` join already satisfies the charset
    with room to spare; no base64/URL-encoding needed for IDs this bot
    itself generates.
    """
    mode = mode if mode in ("practice", "exam") else "practice"
    return f"play_{qid}_{mode}"


def mini_app_startapp_url(bot_username: str, qid: str, mode: str = "practice") -> Optional[str]:
    """`https://t.me/<bot>?startapp=play_<qid>_<mode>` deep link.

    This is the ONLY link type that opens a Mini App as a true WebApp
    session (populated `initData`, native theming/haptics/MainButton) from
    a context where a `web_app=` button isn't allowed -- e.g. an inline
    query result shared into any chat. A plain HTTPS link to the play page
    opens in Telegram's in-app browser instead, where `initData` is empty
    and the mini app cannot authenticate (see index.html's boot()).

    Requires the Mini App to be registered with @BotFather (Bot Settings ->
    Configure Mini App / Web App) pointing at the `/play` URL -- otherwise
    `startapp` falls back to a plain `/start` with no app launch. Returns
    None if the Mini App isn't configured (no MINI_APP_DOMAIN).

    The mini app reads the payload via
    `Telegram.WebApp.initDataUnsafe.start_param` once launched (see
    index.html's boot(), which checks this before falling back to the URL
    path) -- NOT from the play page's own URL, since `startapp` never
    navigates the WebApp to a URL containing the payload itself.
    """
    if not config.MINI_APP_DOMAIN:
        return None
    payload = _startapp_payload(qid, mode)
    return f"https://t.me/{bot_username}?startapp={payload}"


def mini_app_startapp_button_pyrogram(bot_username: str, qid: str, mode: str, label: Optional[str] = None):
    """A plain `url=` InlineKeyboardButton (Pyrogram) pointing at the
    `?startapp=` deep link -- safe on inline query results and in groups,
    and (unlike a direct HTTPS link) actually opens a real Mini App WebApp
    session. Returns None if the Mini App is not configured."""
    url = mini_app_startapp_url(bot_username, qid, mode)
    if not url:
        return None
    from pyrogram.types import InlineKeyboardButton

    text = label or ("Play (Practice)" if mode == "practice" else "Play (Exam)")
    return InlineKeyboardButton(text, url=url)


def mini_app_link_button_pyrogram(qid: str, mode: str, label: Optional[str] = None):
    """A plain `url=` InlineKeyboardButton (Pyrogram) -- safe anywhere,
    including inline query results and group chats. Returns None if the
    Mini App is not configured."""
    url = mini_app_play_url(qid, mode)
    if not url:
        return None
    from pyrogram.types import InlineKeyboardButton

    text = label or ("Play (Practice)" if mode == "practice" else "Play (Exam)")
    return InlineKeyboardButton(text, url=url)


def mini_app_link_button_ptb(qid: str, mode: str, label: Optional[str] = None):
    """A plain `url=` InlineKeyboardButton (python-telegram-bot). Returns
    None if the Mini App is not configured."""
    url = mini_app_play_url(qid, mode)
    if not url:
        return None
    from telegram import InlineKeyboardButton

    text = label or ("Play (Practice)" if mode == "practice" else "Play (Exam)")
    return InlineKeyboardButton(text, url=url)


def mini_app_web_app_button_ptb(qid: str, mode: str, label: Optional[str] = None):
    """A native `web_app` InlineKeyboardButton (python-telegram-bot) -- only
    safe in a private chat with the bot. Returns None if not configured."""
    url = mini_app_play_url(qid, mode)
    if not url:
        return None
    from telegram import InlineKeyboardButton, WebAppInfo

    text = label or ("Play (Practice)" if mode == "practice" else "Play (Exam)")
    return InlineKeyboardButton(text, web_app=WebAppInfo(url=url))
